permissions:
  contents: write
  actions: write

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_macos_x64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Extract tag name
        id: get_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build gui
        run: |
          go mod tidy
          go build -o "g90updatefwgui_macos_x64_${TAG_NAME}"
          chmod +x "g90updatefwgui_macos_x64_${TAG_NAME}"
          zip "G90UpdateFwGui_${TAG_NAME}_macOS_x64.zip" "g90updatefwgui_macos_x64_${TAG_NAME}"

      - name: Release macOS x64 gui
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: G90UpdateFwGui_${{ env.TAG_NAME }}_macOS_x64.zip

  build_windows_x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Extract tag name
        id: get_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        shell: bash

      - name: Build gui
        run: |
          go mod tidy
          go build -o "g90updatefwgui_windows_x64_${{ env.TAG_NAME }}.exe"
          Compress-Archive -Path "g90updatefwgui_windows_x64_${{ env.TAG_NAME }}.exe" -DestinationPath "G90UpdateFwGui_${{ env.TAG_NAME }}_Windows_x64.zip"

      - name: Release Windows x64 gui
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: G90UpdateFwGui_${{ env.TAG_NAME }}_Windows_x64.zip

  build_linux_x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Extract tag name
        id: get_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build gui
        run: |
          sudo apt update && sudo apt install gcc libgtk-3-dev libgl1-mesa-dev xorg-dev libxkbcommon-dev -y
          go mod tidy
          go build -o "g90updatefwgui_linux_x64_${TAG_NAME}"
          chmod +x "g90updatefwgui_linux_x64_${TAG_NAME}"
          zip "G90UpdateFwGui_${TAG_NAME}_Linux_x64.zip" "g90updatefwgui_linux_x64_${TAG_NAME}"

      - name: Release Linux x64 gui
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: G90UpdateFwGui_${{ env.TAG_NAME }}_Linux_x64.zip
